# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b314b4fdc8c2502af8c88334d105b49a2c4cfd4759b6221d122333749fa1510cbfbd7b755436d8f921de85f37067c9038c6a3c573bdb4689e2daff96992356c3

test:
  secret_key_base: dd82850a1647c93c3a6d5883779f9c64343515f61350bdee81ed1bcf2d3cdbebb336b91ba99e4dc02180cf4adf3e5298ac7de8509417f5cfdbe4aba7de316862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
